default: &default

  # Ruta de la llave pública descargada desde flow.cl
  key_publica : flow_keys/flow.pubkey

  # Modo de acceso a webpay, valores posibles:
  ### - Mostrar pasarela flow : f
  ### - Ingresar directamente a webpay : d
  tipo_pago : d

  # Medio de pago, valores posibles:
  ### - Solo Webpay : 1
  ### - Solo Servipag : 2
  ### - Todos los medios de pago : 9
  medio_pago : 1

  # Rutas por defecto
  ### Se pueden cambiar, pero deberás agregarlas manualmente a tu archivo config/routes.rb
  url_exito : /flow/exito
  url_fracaso : /flow/fracaso
  url_confirmacion : /flow/confirma

development:
  <<: *default
  # La URL de tu sitio en modo desarrollo, por default localhost
  url : http://localhost:3000

  # email_tienda : mirko@charly.io
  # key_privada : flow_keys/charly_cert.pem
  # url_form : http://flow.tuxpan.com/app/kpf/pago.php
  email_tienda : mirko.scherer@gmx.net
  key_privada : flow_keys/mirko.pem
  url_form : https://www.flow.cl/app/kpf/pago.php

production:
  <<: *default
  # Tu correo de registro en flow.cl
  email_tienda : mirko.scherer@gmx.net

  # La URL de tu sitio en modo producción
  url : http://misitio.cl

  # Ruta de tu llave privada de comercio en producción
  key_privada : flow_keys/mirko.pem

  # Formulario de desarrollo de Flow
  url_form : https://www.flow.cl/app/kpf/pago.php
